version: '3'
services:
    web:
        build:
              context: .
              dockerfile: Dockerfile
        ports:
            - 8080:80
        volumes:
           - .:/var/www/html
        depends_on:
                - db
        networks:
            - app-network
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: docker
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - app-network
networks:
      app-network:
volumes:
      db-data:
